{application,pet_project,
             [{optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger]},
              {description,"pet_project"},
              {modules,['Elixir.PetProject','Elixir.PetProject.Application',
                        'Elixir.Tram']},
              {registered,[]},
              {vsn,"0.1.0"},
              {mod,{'Elixir.PetProject.Application',[]}}]}.
